Issue52.1
zwall-bp/HDRICalibrationTool-Capstone pull request #29
Opened 2024-03-16 16:01 UTC by stack461

Edited the README file to include the user instructions.

2024-03-18 19:48 UTC, adulbrich requested changes, later dismissed

2024-03-18 19:48 UTC, adulbrich commented on README.md
> +**Uploading Images**
Why not use `###` for a level 3 header instead of bold text?

2024-03-18 19:48 UTC, adulbrich commented on README.md
> +The purpose of this application is to give the user a graphical user interface for the Radiance/HDRGen pipeline process. The program works by taking in image files and calibration files in order to r
For the introduction, you might want to check the original repository's README https://github.com/radiantlab/HDRICalibrationTool has it was vetted by Clotilde already?

2024-03-18 19:48 UTC, adulbrich commented on README.md
> +Click on the settings tab in the left hand navigation sidebar and you should see a settings display appear. For the Radiance path, give the path to the Radiance binaries. This would be something like
For code or file paths, you might want to use backticks `` to render it, e.g., `/usr/local/radiance/bin/`

2024-03-18 19:48 UTC, adulbrich commented on README.md
> +The user must install [Radiance](https://www.radiance-online.org/) as well as [HDRGen](http://www.anyhere.com/) to their local machine and have access to their location. After the dependencies have b
In the future, the link to binaries will need to change as this points to a specific run of GitHub Actions but it should point to the latest "stable" release.

2024-03-18 19:49 UTC, adulbrich commented
Once the PR is ready, I'd recommend rebasing before merging to cleanup the commit history 🥇

2024-04-02 01:19 UTC, shantimorrell approved these changes, later dismissed
This looks like a good overview of the app!

2024-04-10 19:19 UTC, shantimorrell approved these changes
Looks good!

2024-04-11 12:02 UTC, merged